name: 🐞 Bug Report
description: Let us know if something is not working as expected!
labels: [bug, triage]
body:
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: 'A clear and concise description of what is currently happening.'
    validations:
      required: true

  - type: textarea
    id: expected_behaviour
    attributes:
      description: 'How is the expected behavior different from what is currently happening?'
      label: Expected Behaviour
    validations:
      required: true

  - type: input
    id: repo
    attributes:
      label: Github Repo
      description: |
        This is extremely important! If possible, please do take a few minutes of your time to create a repo to help us reproduce the issue.
        This is the best way to help us reproduce the issue and fix it as soon as possible.

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide some instructions to reproduce the issue in the repo provided above. Be as detailed as possible.
      value: |
        1.
    validations:
      required: true

  - type: textarea
    id: nx-report
    attributes:
      label: Nx Report
      description: Please paste the contents shown by `nx report`. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Failure Logs
      description: Please include any relevant log snippets or files here. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Information
      description: 'Add any other context or screenshots about the bug here.'
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/nxkit/nxkit/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
